### ISSUE TITLE
Vibration issue Mi 9 SE

### ISSUE THREAD

**Issue by emilic14** [xiaomi-sdm710-devs/android_device_xiaomi_sdm710-common#1]
Hello,

My mi 9 se running lineage of @SebaUbuntu has no vibration.
We think its coming from [this ](https://github.com/LineageOS/android_device_xiaomi_sdm710-common/commit/b8716160090956be12b449fab42d2faa0e09d75d) change.
Other users are having issues that the vibration is way to low and cant modify it.

NOTE, shutting down and turning on my phone does gets the vibration working, so I am sure its a SW issue.

**Comment by SebaUbuntu** [comment]
Please use LineageOS's GitLab for reporting bugs
